services:
  auth_service:
    build: ./AuthService
    ports:
      - 8002:8000
    env_file:
      - ./AuthService/app/.env
  user_service:
    build: ./UserService
    ports:
      - 8003:8000
    env_file:
      - ./UserService/app/.env
  discussion_service:
    build: ./DiscussionService
    ports:
      - 8001:8000
    env_file:
      - ./DiscussionService/app/.env
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - user_service
      - discussion_service